### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Dwikso** [2nthony/dotfiles#27]
Hello i want to know how did u get this on ur neovim .?

![image](https://github.com/user-attachments/assets/13a52966-c30b-40cf-a73c-26526a2cf05b)

thank you in advance for your reply

**Comment by 2nthony** [comment]
I remember this is from https://github.com/nvimdev/lspsaga.nvim , not really sure for now, because I disabled for a long time.

**Comment by Dwikso** [comment]
Ok thx u
